name: active_fit
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.6.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  collection: ^1.19.0
  intl: ^0.19.0
  get_it: ^8.0.3
  provider: ^6.1.2
  http: ^1.2.2
  uuid: ^4.5.1
  json_annotation: ^4.9.0
  logging: ^1.3.0
  path_provider: ^2.1.5
  flutter_secure_storage: ^9.2.2
  package_info_plus: ^8.1.2
  url_launcher: ^6.3.1
  flutter_svg: ^2.0.16
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  envied: ^1.0.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  percent_indicator: ^4.2.4
  horizontal_picker: ^1.2.0
  table_calendar: ^3.1.3
  introduction_screen: ^3.1.14
  auto_size_text: ^3.0.0
  animated_flip_counter: ^0.3.4
  mobile_scanner: ^6.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_fonts: ^6.2.1
  sentry_flutter: ^8.11.2
  font_awesome_flutter: ^10.8.0
  #firebase flutter
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.3
  firebase_messaging: ^15.1.3
  firebase_auth: ^5.3.1
  google_sign_in: ^6.3.0
  image_picker: ^1.1.2
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  fluttertoast: ^8.2.12
  shared_preferences: ^2.5.2
  conditional_builder_null_safety: ^0.0.6
  flutter_localization: ^0.3.1
  fl_chart: ^0.70.2
  flutter_facebook_auth: ^7.1.1
  flutter_launcher_icons: ^0.14.3
  supabase_flutter: ^2.8.4
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  envied_generator: ^1.0.0
  mockito: ^5.4.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icon/

  fonts:
    - family: CustomIcons
      fonts:
      - asset: fonts/CustomIcons.ttf
    - family: Poppins
      fonts:
      - asset: fonts/Poppins-Black.ttf
      - asset: fonts/Poppins-BlackItalic.ttf
        style: italic
      - asset: fonts/Poppins-Bold.ttf
      - asset: fonts/Poppins-BoldItalic.ttf
        style: italic
      - asset: fonts/Poppins-ExtraBold.ttf
      - asset: fonts/Poppins-ExtraBoldItalic.ttf
        style: italic
      - asset: fonts/Poppins-ExtraLight.ttf
      - asset: fonts/Poppins-ExtraLightItalic.ttf
        style: italic
      - asset: fonts/Poppins-Italic.ttf
        style: italic
      - asset: fonts/Poppins-Light.ttf
      - asset: fonts/Poppins-LightItalic.ttf
        style: italic
      - asset: fonts/Poppins-Medium.ttf
      - asset: fonts/Poppins-MediumItalic.ttf
        style: italic
      - asset: fonts/Poppins-Regular.ttf
      - asset: fonts/Poppins-SemiBold.ttf
      - asset: fonts/Poppins-SemiBoldItalic.ttf
        style: italic
      - asset: fonts/Poppins-Thin.ttf
      - asset: fonts/Poppins-ThinItalic.ttf
        style: italic

flutter_intl:
  enabled: true

flutter_launcher_icons:
  android: true
  adaptive_icon_foreground: "assets/icon/active_logo_square.png"
  adaptive_icon_background: "#ffffff"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/active_logo_square.png"
  min_sdk_android: 21


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package